baseURL = 'https://cbbaker.github.io/'
languageCode = 'en-us'
title = 'Half-bakery'
theme = 'ananke'

[markup.goldmark.renderer]
  unsafe = true


[caches]
  [caches.images]
    dir = ':cacheDir/images'
